export const login_Actions = {
	login_SignIn: {
		NEW: "NEW_PAGE",
		HOME: "LOGIN_ACCOUNT_NEW",
		USER: "USER",
		ORDER: "ORDER",
		LOGIN: "LOGIN",
		SELLER: "SELLER_LOGIN",
		DASH: "DASH",
		FOUND: "ACCOUNT_FOUND",
		ACCOUNTS:"ACCOUNTS",
		NOT_FOUND: "ACCOUNT_NOT_FOUND",
	}
}


export const login_Status = {
	login_SignIn: {
		NEW: "NEW_PAGE",
		ACCOUNTS:"ACCOUNTS",
		HOME: "LOGIN_ACCOUNT_NEW",
		USER: "USER",
		ORDER: "ORDER",
		LOGIN: "LOGIN",
		SELLER: "SELLER_LOGIN",
		DASH: "DASH",
		FOUND: "ACCOUNT_FOUND",
		NOT_FOUND: "ACCOUNT_NOT_FOUND",
	}
}
